Models/ErrorViewModel.cs
namespace Avaliacao3BimLP3.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ViewModels/LojaViewModel.cs
namespace Avaliacao3BimLP3.ViewModels;

public class LojaViewModel
{
    public int Id { get; set; }
    public string Piso { get; set; }
    public string Nome { get; set; }   
    public string Descricao { get; set; }
    public bool IsLoja { get; set; }
    public string Email  { get; set; }

    public LojaViewModel(int id, string piso, string nome, string descricao, bool isLoja, string email)
    {
        Id = id;
        Piso = piso;
        Nome = nome;
        Descricao = descricao;
        IsLoja = isLoja;
        Email = email;
    }

    public LojaViewModel(){}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Avaliacao3BimLP3.Models;

namespace Avaliacao3BimLP3.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LojaController.cs
using Microsoft.AspNetCore.Mvc;
using Avaliacao3BimLP3.ViewModels;

namespace Avaliacao3BimLP3.Controllers;

public class LojaController : Controller
{

    private static List<LojaViewModel> lojas =
    new List<LojaViewModel> {
        new LojaViewModel(1, "piso 3", "Tênis Brasil", "Aqui você encontra os tênis", true, "tenis@email.com"),
        new LojaViewModel(2, "piso 3", "Lembranças Já", "Vem comprar sua lembrança", true, "lemb@email.com"),
        new LojaViewModel(3, "piso 1", "Sorvetinho Gelado", "Sorvetinho Gelado", false, "sorvet@email.com"),
    };

    public IActionResult Index()
    {
        return View(lojas);
    }

    public IActionResult AdminIndex()
    {
        return View(lojas);
    }

    public IActionResult AdminShow(int id)
    {
        foreach (var loja in lojas)
        {
            if (loja.Id == id)
            {
                return View(loja);
            }
        }
        return View(); // nunca vai cair aqui se passar um Id válido, entretanto poderia retornar uma mensagem para valores válidos

    }

    public IActionResult AdminDelete(int id)
    {
        for(int i =0 ; i< lojas.Count(); i++)
        {
            if (lojas[i].Id == id)
            {
                lojas.RemoveAt(i);
            } 
        }
        return View("AdminDeleteResult");
    }

    public IActionResult AdminCreate()
    {
        return View();
    }

    public IActionResult AdminResult([FromForm] LojaViewModel lojaCreate)
    {
        foreach (var loja in lojas)
        {
            if (loja.Nome == lojaCreate.Nome)
            {
                return View("CreateError");
            }
        }
        // LojaViewModel lojaCreate = new LojaViewModel(lojaCreate.Id, lojaCreate.Piso, lojaCreate.Nome, lojaCreate.Descricao, lojaCreate.IsLoja, lojaCreate.Email);
        lojas.Add(lojaCreate);
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Loja/AdminCreate.cshtml
@{
    ViewData["Title"] = "Cadastrar Loja";
}

<div class="text-center">
    <h3 class="display-4">Cadastrar Loja</h3>
</div>

<form action="AdminResult" method="post">
    <label for="Id">Id</label> <br>
    <input type="number" name="Id" id="Id"> <br><br>

    <label for="Piso">Tipo:</label> <br>
    <select name="Piso">
        <option value="Piso 1">Piso 1</option>
        <option value="Piso 2">Piso 2</option>
        <option value="Piso 3">Piso 3</option>
    </select> <br> <br>

    <label for="Nome">Nome</label> <br>
    <input type="text" name="Nome" id="Nome"> <br><br>

    <label for="Descricao">Descrição</label> <br>
    <input type="text" name="Descricao" id="Descricao"> <br><br>

    <label for="IsLoja">Tipo:</label> <br>
    <select name="IsLoja">
        <option value="true">Loja</option>
        <option value="false">Kiosque</option>
    </select> <br> <br>

    <label for="Email">E-mail</label> <br>
    <input type="email" name="Email" id="Email"> <br><br>

    <button type="submit">Enviar</button>
</form>

Views/Loja/AdminDeleteResult.cshtml
@model List<Avaliacao3BimLP3.ViewModels.LojaViewModel>

@{
    ViewData["Title"] = "Resultado do forms";
}

<p>Apagado com sucesso, volte  <a href="../AdminIndex"> <b>aqui</b> </a> </p>

Views/Loja/AdminIndex.cshtml
@model List<Avaliacao3BimLP3.ViewModels.LojaViewModel>

@{
    ViewData["Title"] = "Gerenciar lojas";
}

<div class="text-center">
    <h1 class="display-4">Gerenciar lojas</h1>
</div>

@if(Model.Count == 0)
{
    <p>Não há lojas e kiosques cadastrados</p>
}
else 
{
<p> @Model.Count lojas cadastradas </p>

@foreach (var loja in Model)
{
    <p> @loja.Piso </p>
    <p> @loja.Nome </p>
    <p> @loja.Descricao </p>

   if (loja.IsLoja) 
   {
   <p> Loja </p>
   }
   else 
   {
   <p> Kiosque </p>
   }
   <a href="AdminShow/@loja.Id"> <button type="button"> Detalhes </button> </a>
   <a href="AdminDelete/@loja.Id"> <button type="button"> Excluir Loja </button> </a>
   <hr>
    }
}

Views/Loja/AdminResult.cshtml
@model List<Avaliacao3BimLP3.ViewModels.LojaViewModel>

@{
    ViewData["Title"] = "Resultado do forms";
}

<p>Loja cadastrada volte  <a href="../Loja/AdminIndex"> <b>aqui</b> </a> </p>

Views/Loja/AdminShow.cshtml
@model Avaliacao3BimLP3.ViewModels.LojaViewModel;

@{
    ViewData["Title"] = "Estudante: ";
}

<h1> @Model.Id </h1>

<p> Piso: @Model.Piso </p>
<p> Nome: @Model.Nome </p>
<p> Descrição: @Model.Descricao </p>
@if(@Model.IsLoja)
{
    <p> Tipo: Loja </p>
}
else 
{
    <p> Tipo: Kiosque </p>
}
   <a href="../AdminDelete/@Model.Id"> <button type="button"> Excluir Loja </button> </a>

Views/Loja/CreateError.cshtml
@model List<Avaliacao3BimLP3.ViewModels.LojaViewModel>

@{
    ViewData["Title"] = "Resultado do forms";
}

<p>Já existe uma loja/kiosque com esse nome</p>

Views/Loja/Index.cshtml
@model List<Avaliacao3BimLP3.ViewModels.LojaViewModel>

@{
    ViewData["Title"] = "Lista de Lojas";
}

<div class="text-center">
    <h1 class="display-4">Lista de lojas</h1>
</div>

@if(Model.Count == 0)
{
    <p>Não há lojas e kiosques cadastrados</p>
}
else 
{
<p> @Model.Count lojas cadastradas </p>

@foreach (var loja in Model)
{
    <p> @loja.Piso </p>
    <p> @loja.Nome </p>
    <p> @loja.Descricao </p>
   if (loja.IsLoja)
   {
   <p> Loja </p>
   }
   else 
   {
   <p> Kiosque </p>
   }
   <hr>
}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avaliacao3BimLP3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Avaliacao3BimLP3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Avaliacao3BimLP3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loja" asp-action="Index">Lista de Lojas</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loja" asp-action="AdminIndex">Gerenciar Lojas</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loja" asp-action="AdminCreate">Cadastrar Loja</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Avaliacao3BimLP3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>